In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
from sklearn.model_selection import cross_val_predict
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
clean = pd.read_csv("autoclean.csv")
clean.head()

,Unnamed: 0,length,width,curb-weight,engine-size,horsepower,city-L/100km,highway-L/100km,wheel-base,bore,drive-wheels,price
0,0,0.811148,0.890278,2548,130,111,11.190476,8.703704,88.6,3.47,rwd,13495
1,1,0.811148,0.890278,2548,130,111,11.190476,8.703704,88.6,3.47,rwd,16500
2,2,0.822681,0.909722,2823,152,154,12.368421,9.038462,94.5,2.68,rwd,16500
3,3,0.848630,0.919444,2337,109,102,9.791667,7.833333,99.8,3.19,fwd,13950
4,4,0.848630,0.922222,2824,136,115,13.055556,10.681818,99.4,3.19,4wd,17450

In [3]:
clean.drop(["drive-wheels","Unnamed: 0"], axis = 1, inplace=True)
clean.head()

,length,width,curb-weight,engine-size,horsepower,city-L/100km,highway-L/100km,wheel-base,bore,price
0,0.811148,0.890278,2548,130,111,11.190476,8.703704,88.6,3.47,13495
1,0.811148,0.890278,2548,130,111,11.190476,8.703704,88.6,3.47,16500
2,0.822681,0.909722,2823,152,154,12.368421,9.038462,94.5,2.68,16500
3,0.848630,0.919444,2337,109,102,9.791667,7.833333,99.8,3.19,13950
4,0.848630,0.922222,2824,136,115,13.055556,10.681818,99.4,3.19,17450

In [4]:
clean.corr()

,length,width,curb-weight,engine-size,horsepower,city-L/100km,highway-L/100km,wheel-base,bore,price
length,1.000000,0.857170,0.880665,0.685025,0.579795,0.657373,0.707108,0.876024,0.608971,0.690628
width,0.857170,1.000000,0.866201,0.729436,0.615056,0.673363,0.736728,0.814507,0.544885,0.751265
curb-weight,0.880665,0.866201,1.000000,0.849072,0.757981,0.785353,0.836921,0.782097,0.644060,0.834415
engine-size,0.685025,0.729436,0.849072,1.000000,0.822668,0.745059,0.783465,0.572027,0.572609,0.872335
horsepower,0.579795,0.615056,0.757981,0.822668,1.000000,0.889482,0.840627,0.371178,0.566903,0.809607
city-L/100km,0.657373,0.673363,0.785353,0.745059,0.889482,1.000000,0.958306,0.476153,0.554610,0.789898
highway-L/100km,0.707108,0.736728,0.836921,0.783465,0.840627,0.958306,1.000000,0.577576,0.559112,0.801118
wheel-base,0.876024,0.814507,0.782097,0.572027,0.371178,0.476153,0.577576,1.000000,0.493244,0.584642
bore,0.608971,0.544885,0.644060,0.572609,0.566903,0.554610,0.559112,0.493244,1.000000,0.543155
price,0.690628,0.751265,0.834415,0.872335,0.809607,0.789898,0.801118,0.584642,0.543155,1.000000

In [5]:
x = clean[['length','width','horsepower', 'curb-weight', 'engine-size', 'highway-L/100km']]
y = clean['price']length

In [6]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15, random_state=0)

In [7]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [8]:
y_pred = lr.predict(x_test)
y_pred[:5]

array([ 4892.18648689, 10799.07766298, 19454.61354283, 21647.86783925,
       19459.70018362])

In [9]:
y_test = np.array(y_test.astype("float"))
y_test[:5]

array([ 6295., 10698., 13860., 13499., 15750.])

In [12]:
from sklearn.metrics import accuracy_score
lr.score(x_test,y_test)

0.7663619101068349